---
title: "RDev Proposal"
author: "Eunkwang"
date: '2017 7 9 '
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## 작성배경

1. 본 문서는 R Dev Study 그룹에서 진행했으면 하는 프로젝트를 제안하기위한 목적으로 작성하였습니다.
2. 프로젝트를 통해 달성하고자 하는 목표는 2가지 입니다.
    - R 활용 스킬 학습
    - 추상적 분석 스킬의 구체화

## 세부 제안

* 학습 중심의 스터디
* 분석 애플리케이션 개발 프로젝트

## R 스킬 향상을 위한 스터디

* Rstudio 에서 제공하는 기능에 대한 스터디
    - Rstudio Server 사용방법
    - DB 연동
    - 프로젝트 단위 관리
    - 버전관리 협업 방법
    - 캐릭터 인코딩
    - rmarkdown 사용 방법
    - 프로파일링 사용 방법
    - 배치 처리기

## R 스킬 향상을 위한 스터디

* 데이터집계와 재구조화를 위한 스터디
    - 집계(dplyr)
    - 데이터재구조화(tidyr)
        + 매트릭스 재표현 하기
    - 배열 처리
        + Loop 처리와 배열 처리의 처리 속도 벤치마킹 하기

## R 스킬 향상을 위한 스터디

* 머신러닝
    - 머신러닝 패키지의 모델링 정확도와 속도 벤치마킹 하기
    - 딥러닝(tensorflow with R)
* 이론관련 스터디(희망사항)
    - PGM(Probability Graph Modeling)
    - 최적화

## 간단히 진행해볼 수 있는 프로젝트 1/3

* 네이버 연관 검색어 추출 저장 프로그램 만들기(http://soke.tistory.com/128)
    - 필요한 지식 :R, 크롤링, 텍스트 분석, DB
    - 분석에 필요한 키워드 준비
    - 네이버 검색 페이지의 페이지 구조 파악
    - 분석 키워드별로 분석 페이지 크롤링
    - 집계
    - DB 저장석

## 간단히 진행해볼 수 있는 프로젝트 2/3

* 날씨 온도 데이터를 활용한 시계열 anomaly detection
    - 필요한 지식 :R, 시계열데이터분석
    - 기상 정보 제공 API 활용법 확인
    - API를 호출
    - 수집한 데이터를 시계열 데이터로 변환
    - 시계열 예측
        
## 간단히 진행해볼 수 있는 프로젝트 3/3

* 승패기록 기반의 가위바위보 프로그램 만들기
    - 필요한 기술 : R, DB
    - 데이터가 없을 때 작동하는 가위바위보 알고리즘 개발
    - 승패 기록을 저장
    - 경기가 x회 이상 진행되었을 때 승패 기록 기반으로 한 가위바위보 알고리즘 개발
    - 가위바위보 결과에 따라 승율이 어떻게 계산되는지 시각화
    
* 안드로이드폰 Tasker 를 활용한 Push 문자 분석하기
    - 필요한 지식 : R, DB, Tasker
    - 안드로이드폰에서 분석하고 싶은 문자의 종류를 선정
    - Tasker를 이용하여 DB에 관련 데이터를 입력하게 처리
        - 실시간으로 처리할지 아니면 파일 전송 방식을 선택할지 결정
